version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "automerge"
    # Group all updates together
    groups:
      dependencies:
        patterns:
          - "*"
    # Set reviewers for pull requests
    reviewers:
      - "victorlucss"
    # Limit the number of open pull requests
    open-pull-requests-limit: 10

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "automerge"
    groups:
      github-actions:
        patterns:
          - "*"
    reviewers:
      - "victorlucss"
